# Generated by Django 4.1.3 on 2023-02-21 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_color_phone_item_color_alter_item_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='color',
            new_name='Color',
        ),
        migrations.RenameField(
            model_name='phone_item',
            old_name='color',
            new_name='Color',
        ),
    ]
