# Generated by Django 4.1.3 on 2023-02-21 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='Color',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='phone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.phone'),
        ),
        migrations.AlterField(
            model_name='item',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.warehouse'),
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.color'),
        ),
    ]
