# Generated by Django 4.1.3 on 2023-02-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='model',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
