# Generated by Django 4.1.3 on 2023-02-23 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_alter_phone_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='users',
            field=models.ManyToManyField(related_name='warehouses', to=settings.AUTH_USER_MODEL),
        ),
    ]
