# Generated by Django 4.1.3 on 2023-02-23 22:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_alter_warehouse_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='users',
            field=models.ManyToManyField(default=None, related_name='warehouses', to=settings.AUTH_USER_MODEL),
        ),
    ]
