# Generated by Django 4.1.3 on 2023-02-23 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_warehouse_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='users',
        ),
    ]
