# Generated by Django 4.1.3 on 2023-02-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
