# Generated by Django 4.1.3 on 2023-02-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_activewarehouse_userprofile_active_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_warehouses',
            field=models.ManyToManyField(related_name='assigned_users', to='api.warehouse'),
        ),
    ]
