# Generated by Django 4.1.3 on 2023-03-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_useraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraction',
            name='item_id',
        ),
        migrations.AddField(
            model_name='useraction',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.warehouse'),
        ),
    ]
