# Generated by Django 4.1.3 on 2023-03-06 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_useraction_item_id_useraction_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.item')),
            ],
            options={
                'verbose_name_plural': 'SaleLogs',
            },
        ),
        migrations.DeleteModel(
            name='salesLog',
        ),
        migrations.AddField(
            model_name='useraction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.salelog'),
        ),
    ]
