# Generated by Django 4.1.3 on 2023-03-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_useraction_sale_useraction_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraction',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
